version: '3'

services:
  wall-be-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wallbe_demo
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "13306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: ["mysql", "all"]

  wall-be-postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: ["postgresql", "all"]

  wall-be:
    image: ubuntu:22.04
    volumes:
      - backup_data:/backup
      - ./config:/etc/wall-be
      - ../../:/opt/wall-be
    command: >
      bash -c "apt-get update && 
      apt-get install -y curl mysql-client postgresql-client gzip bzip2 lzop lz4 pigz zstd &&
      mkdir -p /usr/local/bin &&
      chmod +x /opt/wall-be/wall-be.sh &&
      ln -sf /opt/wall-be/wall-be.sh /usr/local/bin/wall-be &&
      mkdir -p /backup/mysql /backup/postgresql &&
      echo '#!/bin/bash' > /usr/local/bin/wal-g-mysql &&
      echo 'source /etc/wall-be/mysql.env' >> /usr/local/bin/wal-g-mysql &&
      echo 'BACKUP_TIME=\$(date +%Y%m%d_%H%M%S)' >> /usr/local/bin/wal-g-mysql &&
      echo 'BACKUP_FILE=\"\$WALG_FILE_PREFIX/mysql_backup_\$BACKUP_TIME.sql\"' >> /usr/local/bin/wal-g-mysql &&
      echo 'mysqldump --host=\"\$WALG_MYSQL_HOST\" --user=\"\$WALG_MYSQL_USER\" --password=\"\$WALG_MYSQL_PASSWORD\" --port=\$WALG_MYSQL_PORT --all-databases --single-transaction > \"\$BACKUP_FILE\"' >> /usr/local/bin/wal-g-mysql &&
      echo 'gzip -f \"\$BACKUP_FILE\"' >> /usr/local/bin/wal-g-mysql &&
      echo 'echo \"Backup created: \$BACKUP_FILE.gz\"' >> /usr/local/bin/wal-g-mysql &&
      chmod +x /usr/local/bin/wal-g-mysql &&
      echo '#!/bin/bash' > /usr/local/bin/wal-g-pg &&
      echo 'source /etc/wall-be/postgres.env' >> /usr/local/bin/wal-g-pg &&
      echo 'BACKUP_TIME=\$(date +%Y%m%d_%H%M%S)' >> /usr/local/bin/wal-g-pg &&
      echo 'BACKUP_FILE=\"\$WALG_FILE_PREFIX/pg_backup_\$BACKUP_TIME.sql\"' >> /usr/local/bin/wal-g-pg &&
      echo 'PGPASSWORD=\"\$PGPASSWORD\" pg_dump -h \"\$PGHOST\" -U \"\$PGUSER\" -p \$PGPORT -d \"\$PGDATABASE\" > \"\$BACKUP_FILE\"' >> /usr/local/bin/wal-g-pg &&
      echo 'gzip -f \"\$BACKUP_FILE\"' >> /usr/local/bin/wal-g-pg &&
      echo 'echo \"Backup created: \$BACKUP_FILE.gz\"' >> /usr/local/bin/wal-g-pg &&
      chmod +x /usr/local/bin/wal-g-pg &&
      sleep infinity"
    profiles: ["mysql", "postgresql", "all"]

volumes:
  mysql_data:
  postgres_data:
  backup_data: 